# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5eaa3014405783d424db541470df52ad3d20016cf7f312a4cb6e05fb7f249fb8a8afc4a768714301a24c63f4fbc128e4fb8698e25d783f4261c949406d2ec33f

test:
  secret_key_base: 9e19ccc149051df6fc699d0f6536b38b3a8aa496c9c718b910a7d6d578b0af9e067e9f9162645e5009047ef9b612def86bf7f32ae1e50547efd5edadcde4e344

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
